name: Production Firebase Deployment
on:
  push:
    branches:
      - 'main'
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '14'
      - name: Install NPM Dependencies
        run: npm install
      - name: Build Application
        run: npm run build
      - name: Install Firebase Tools
        run: npm install firebase-tools -g
      - name: Deploy to Firebase
        run: firebase deploy --project nfrost-dev --token "${{ secrets.FIREBASE_TOKEN }}" -m "${{ github.event.head_commit.message }}"
      - name: Run Lighthouse Audit
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          urls: 'https://www.nfrost.dev,https://www.nfrost.dev/kvcc-department-directory'
      - name: Validate Lighthouse Check
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "100"
          minBestPracticesScore: "100"
          minPerformanceScore: "50"
          minSeoScore: "100"
